export const DATA_FETCH_REQUEST = "DATA_FETCH_REQUEST";
export const DATA_FETCH_SUCCESS = "DATA_FETCH_SUCCESS";
export const DATA_FETCH_FAILURE = "DATA_FETCH_FAILURE";
export const SORT_ASC = "SORT_ASC";
export const SORT_DESC = "SORT_DESC";
export const SEARCH_CONTACT = "SEARCH_CONTACT";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const DELETE_FAVORITE = "DELETE_FAVORITE";
